# Generated by Django 3.2.7 on 2021-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Cash', 'Cash')], default='Cash', max_length=15),
        ),
    ]
